name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v13
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was added"
          done
      - name: basic
        if: contains(github.ref, 'refs/tags/basic')
        run: cd packages/basic
      - name: typescript
        if: contains(github.ref, 'refs/tags/typescript')
        run: cd packages/typescript
      - name: react
        if: contains(github.ref, 'refs/tags/react')
        run: cd packages/react
      - name: vue
        if: contains(github.ref, 'refs/tags/vue')
        run: cd packages/vue
      - run: npm i -g npm @antfu/ni
      - run: nci
      - run: nr test --if-present
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GH_TOKEN}}